#!/usr/bin/env node
/**
 * `content/bestiary.json` — the mechanical projection of canon's creatures.
 *
 * Canon owns what a creature *is*; this is what the engine needs to put one on
 * a board. It is generated, never edited: `npm run canon:bestiary` after any
 * change to a creature's `encounter` block, exactly like the art portraits.
 *
 * Keyed by `asset_id` rather than canon id, because that is the join every
 * other consumer already uses — `assets/entities/<asset_id>/assembled.png` is
 * the art, and a chapter's `EnemySpec.art` resolves through the same name.
 *
 * The proof that the bands are right is `will_o_wisp`. `bramblewood-01.json`
 * has shipped a Bramblewisp at hp 6 / guard 11 / quick 3 / steps 5 / attack 3
 * since before any of this existed; the `skirmisher` row was derived from it,
 * and this projection reproduces it exactly. If that ever stops being true,
 * either the band table moved or the chapter did.
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { BANDS, loadCanon, resolveStats, resolveXp, slugOf } from "@kad/canon";
import type { Creature } from "@kad/canon";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const OUT = path.join(ROOT, "content", "bestiary.json");

const registry = loadCanon(path.join(ROOT, "canon"));
const creatures = (registry.byTaxonomy.get("creature") ?? []) as Creature[];

const bestiary: Record<string, unknown> = {};
for (const creature of creatures) {
  if (!creature.encounter) continue;
  const id = creature.asset_id ?? slugOf(creature.id);
  const stats = resolveStats(creature.encounter);
  if (!stats) continue;

  bestiary[id] = {
    name: creature.title,
    art: `enemies/${id}`,
    band: creature.encounter.band,
    ...stats,
    xp: resolveXp(creature.encounter),
    usualCount: BANDS[creature.encounter.band].usualCount,
    ...(creature.encounter.footprint === undefined
      ? {}
      : { footprint: creature.encounter.footprint }),
    ...(creature.encounter.behavior === undefined
      ? {}
      : { behavior: creature.encounter.behavior }),
    resolutions: creature.encounter.resolutions,
  };
}

const doc = {
  $comment:
    "GENERATED by tools/canon/bestiary.ts from canon/creatures.yaml — do not edit. " +
    "Canon is the source of truth (docs/canon-contract.md); run `npm run canon:bestiary`.",
  version: 1,
  creatures: bestiary,
};

fs.writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`${path.relative(ROOT, OUT)} — ${Object.keys(bestiary).length} creatures`);
for (const [id, entry] of Object.entries(bestiary)) {
  const e = entry as { band: string; hp: number; guard: number; quick: number; steps: number; attack: number; xp: number };
  console.log(
    `  ${id.padEnd(20)} ${e.band.padEnd(11)} hp ${String(e.hp).padStart(2)}  guard ${e.guard}  quick ${e.quick}  steps ${e.steps}  attack ${e.attack}  xp ${e.xp}`,
  );
}
