#!/usr/bin/env node
/**
 * `content/items.json` — the catalog the game reads, projected from D7's two
 * authoring homes.
 *
 * Canon owns items the *world* has: a honeycake is baked in Bramblewood every
 * morning whether or not anybody is playing. A chapter owns items that exist
 * only because that chapter happened — the rusted key fits one door, in one
 * story, and asserting it as a fact about the Realm would be a lie told to
 * make a lock work.
 *
 * Both project into one flat namespace here, and that is deliberate rather
 * than lazy. Quest items outlive the chapter that grants them
 * (`character.questItems`), so an inventory screen three chapters later still
 * has to name the key. A per-chapter catalog would make that impossible; a
 * merged one only has to stay collision-free, which is a thing a build can
 * check and a human cannot.
 *
 * Generated, never edited: `npm run canon:items`.
 */

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { loadCanon, mechanicsProblems, slugOf } from "@kad/canon";
import type { Item } from "@kad/canon";
import { itemCatalog } from "@kad/shared";
import type { Chapter, ItemDef } from "@kad/shared";

const ROOT = path.resolve(import.meta.dirname, "..", "..");
const OUT = path.join(ROOT, "content", "items.json");
const CHAPTERS = path.join(ROOT, "content", "chapters");

interface Sourced {
  def: ItemDef;
  /** Where it was authored, for the collision message. */
  from: string;
}

const problems: string[] = [];
const catalog = new Map<string, Sourced>();

function claim(id: string, def: ItemDef, from: string): void {
  const held = catalog.get(id);
  if (held) {
    problems.push(
      `"${id}" is authored twice — ${held.from} and ${from}. ` +
        `The catalog is one namespace: rename the prop, or promote it to canon and drop the prop.`,
    );
    return;
  }
  catalog.set(id, { def, from });
}

// --- canon: what the world has ---------------------------------------------

const registry = loadCanon(path.join(ROOT, "canon"));
for (const item of (registry.byTaxonomy.get("item") ?? []) as Item[]) {
  const { mechanics } = item;
  // No mechanics is a claim, not a gap: the Crystal Heart is canon and is not
  // in anybody's bag. Only playable items project.
  if (!mechanics) continue;
  claim(
    slugOf(item.id),
    {
      kind: mechanics.kind,
      icon: mechanics.icon,
      name: item.title,
      text: mechanics.text,
      ...(mechanics.effect ? { effect: mechanics.effect } : {}),
      ...(mechanics.passive ? { passive: mechanics.passive } : {}),
    },
    `canon/items.yaml (${item.id})`,
  );
}

// --- chapters: what one story brought with it ------------------------------

const chapterFiles = fs.existsSync(CHAPTERS)
  ? fs.readdirSync(CHAPTERS).filter((f) => f.endsWith(".json")).sort()
  : [];

for (const file of chapterFiles) {
  const chapter = JSON.parse(
    fs.readFileSync(path.join(CHAPTERS, file), "utf8"),
  ) as Chapter;
  for (const [id, def] of Object.entries(itemCatalog(chapter.props ?? {}))) {
    // The same kind/effect/passive rule canon items obey. A prop is not a
    // relaxed item, it is an item with a different owner.
    for (const message of mechanicsProblems({
      kind: def.kind,
      icon: def.icon,
      text: def.text,
      effect: def.effect,
      passive: def.passive,
    })) {
      problems.push(`chapters/${file} prop "${id}": ${message}`);
    }
    claim(id, def, `chapters/${file}`);
  }
}

if (problems.length > 0) {
  console.error("content/items.json — cannot project:\n");
  for (const problem of problems) console.error(`  ${problem}`);
  process.exit(1);
}

// `$comment` rather than a wrapper object: items.json is a flat
// Record<itemId, ItemDef> everything already reads, and abilities.json set the
// precedent for a `$`-prefixed key inside one (`$deferred`). Consumers strip
// them through `itemCatalog()` in packages/shared.
const doc: Record<string, unknown> = {
  $comment:
    "GENERATED by tools/canon/items.ts from canon/items.yaml and every chapter's `props` — do not edit. " +
    "Canon is the source of truth (docs/canon-contract.md); run `npm run canon:items`.",
};

// Sorted by kind, then id: the file is read by humans reviewing a diff, and
// grouping consumables together is the ordering it has always had by hand.
const ORDER: Record<string, number> = { consumable: 0, trinket: 1, quest: 2 };
const sorted = [...catalog.entries()].sort(
  ([aId, a], [bId, b]) =>
    (ORDER[a.def.kind] ?? 9) - (ORDER[b.def.kind] ?? 9) || aId.localeCompare(bId),
);
for (const [id, { def }] of sorted) doc[id] = def;

fs.writeFileSync(OUT, `${JSON.stringify(doc, null, 2)}\n`);

const counts = sorted.reduce<Record<string, number>>((acc, [, { def }]) => {
  acc[def.kind] = (acc[def.kind] ?? 0) + 1;
  return acc;
}, {});
console.log(
  `${path.relative(ROOT, OUT)} — ${sorted.length} items ` +
    `(${Object.entries(counts).map(([k, n]) => `${n} ${k}`).join(", ")})`,
);
for (const [id, { def, from }] of sorted) {
  console.log(`  ${id.padEnd(20)} ${def.kind.padEnd(11)} ${from}`);
}
